In [1]:
import numpy as np
import tensorflow as tf

In [2]:
char_rdic = list('helo')
print(char_rdic)
char_dic = {w: i for i, w in enumerate(char_rdic)}
print(char_dic)
x_data = np.array([
    [1, 0, 0, 0],  # h
    [0, 1, 0, 0],  # e
    [0, 0, 1, 0],  # l
    [0, 0, 1, 0],  # l
], dtype='f')
print(x_data)
sample = [char_dic[c] for c in "hello"]
print(sample)

['h', 'e', 'l', 'o']
{'e': 1, 'h': 0, 'l': 2, 'o': 3}
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  1.  0.]]
[0, 1, 2, 2, 3]


In [4]:
print(len(char_dic))

4


In [5]:
# Configuration
char_vocab_size = len(char_dic)
rnn_size = char_vocab_size  # 1 hot coding (one of 4)
time_step_size = 4  # 'hell' -> predict 'ello'
batch_size = 1  # one sample

# RNN model
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(rnn_size)
state = tf.zeros([batch_size, rnn_cell.state_size])
print rnn_cell.state_size 
X_split = tf.split(0, time_step_size, x_data)
print X_split
outputs, state = tf.nn.rnn(rnn_cell, X_split, state)

# logits: list of 2D Tensors of shape [batch_size x num_decoder_symbols]
# targets: list of 1D batch-sized int32 Tensors of the same length as logits.
# weights: list of 1D batch-sized float-Tensors of the same length as logits.
logits = tf.reshape(tf.concat(1, outputs), [-1, rnn_size])
targets = tf.reshape(sample[1:], [-1])
weights = tf.ones([time_step_size * batch_size])

loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train_op = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)

SyntaxError: Missing parentheses in call to 'print' (<ipython-input-5-5015b0ac1b5f>, line 10)

In [6]:
from tensorflow.python.framework import dtypes

# Configuration
char_vocab_size = len(char_dic)
lstm_size = char_vocab_size  # 1 hot coding (one of 4)
time_step_size = 4  # 'hell' -> predict 'ello'
batch_size = 1  # one sample

# LSTM
lstm_cells = []
lstm_cell1 = tf.nn.rnn_cell.BasicLSTMCell(lstm_size, state_is_tuple=True)
lstm_cell2 = tf.nn.rnn_cell.BasicLSTMCell(lstm_size, state_is_tuple=True)
lstm_cells.append(lstm_cell1)
lstm_cells.append(lstm_cell2)
stacked_lstm = tf.nn.rnn_cell.MultiRNNCell(lstm_cells, state_is_tuple=True)

X_split = tf.split(0, time_step_size, x_data)
print(X_split)
outputs, states = tf.nn.rnn(stacked_lstm, X_split, dtype=dtypes.float32)
print(outputs)

logits = tf.reshape(tf.concat(1, outputs), [-1, lstm_size])
print(logits)
targets = tf.reshape(sample[1:], [-1])
print(targets)
weights = tf.ones([time_step_size * batch_size])

loss = tf.nn.seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train_op = tf.train.AdamOptimizer(0.01).minimize(cost)

AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

In [14]:
# print(X_split)
print(tf.shape(outputs))
print tf.shape(logits)
print tf.shape(weights)
print tf.shape(targets)


Tensor("Shape_15:0", shape=(3,), dtype=int32)
Tensor("Shape_16:0", shape=(2,), dtype=int32)
Tensor("Shape_17:0", shape=(1,), dtype=int32)
Tensor("Shape_18:0", shape=(1,), dtype=int32)
[1, 2, 2, 3]


In [5]:
# Launch the graph in a session
with tf.Session() as sess:
    # you need to initialize all variables
    tf.initialize_all_variables().run()
    for i in range(200):
        sess.run(train_op)
        result = sess.run(tf.arg_max(logits, 1))
        print("%r, %r" % (result, [char_rdic[t] for t in result]))

Instructions for updating:
Use `tf.global_variables_initializer` instead.
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
array([2, 2, 2, 2]), ['l', 'l', 'l', 'l']
ar