In [2]:
import gym
import numpy as np

In [9]:
env = gym.make('FrozenLake-v0')
print(env.observation_space.n)
print(env.action_space.n)

[2016-10-20 11:55:18,018] Making new env: FrozenLake-v0


16
4


In [12]:
#Initialize table with all zeros
Q = np.zeros([env.observation_space.n,env.action_space.n])
print(Q)
# Set learning parameters
lr = .85
y = .99
num_episodes = 2000
#create lists to contain total rewards and steps per episode
#jList = []
rList = []
for i in range(num_episodes):
    #Reset environment and get first new observation
    s = env.reset()
    rAll = 0
    d = False
    j = 0
    #The Q-Table learning algorithm
    while j < 99:
        j+=1
        #Choose an action by greedily (with noise) picking from Q table
        a = np.argmax(Q[s,:] + np.random.randn(1,env.action_space.n)*(1./(i+1)))
        #Get new state and reward from environment
        s1,r,d,_ = env.step(a)
        #Update Q-Table with new knowledge
        Q[s,a] = Q[s,a] + lr*(r + y*np.max(Q[s1,:]) - Q[s,a])
        rAll += r
        s = s1
        if d == True:
            break
    #jList.append(j)
    rList.append(rAll)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [20]:
np.random.randn(1,env.action_space.n)*(1./(0+1))

array([[ 0.2178916 , -0.71107   ,  1.07224234, -0.03751424]])

In [11]:
print "Score over time: " +  str(sum(rList)/num_episodes)
print "Final Q-Table Values"
print Q

Score over time: 0.4795
Final Q-Table Values
[[  3.47228060e-01   4.15027800e-03   1.19168851e-02   7.90382667e-03]
 [  2.83259036e-04   1.17869336e-03   0.00000000e+00   2.68582272e-01]
 [  2.64680415e-01   1.01762947e-03   1.04042940e-03   0.00000000e+00]
 [  0.00000000e+00   1.54060804e-04   0.00000000e+00   1.01505564e-03]
 [  3.00317599e-01   1.91726286e-03   1.47640771e-03   1.85283310e-03]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.09141189e-03   7.98206464e-07   5.99749748e-03   2.77320113e-06]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  1.04609682e-03   1.44049333e-03   0.00000000e+00   1.40882381e-01]
 [  3.83522450e-04   4.95151639e-01   1.12983239e-03   0.00000000e+00]
 [  8.15687821e-01   2.72275348e-04   1.37321328e-04   8.02589705e-05]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e